comprimento = float (input("Digite o comprimento: "))
altura = float (input("Digite a altura: "))
largura = float (input("Digite a largura: "))
temp_desejada = float (input("Digite a temperatura desejada: "))
temp_ambiente = float (input("Digite a temperatura ambiente: "))